import React from 'react';
import Head from 'next/head';

export default function Disclaimer() {
  return (
    <div className="min-h-screen bg-white text-slate-800">
      <Head>
        <title>Disclaimer — Policy2Summary | Insurance Document Analysis Tool</title>
        <meta name="description" content="Policy2Summary disclaimer. Our AI summaries are for informational purposes only and do not replace professional insurance advice." />
        <meta name="robots" content="index, follow" />
        <link rel="canonical" href="https://www.policy2summary.com/disclaimer" />
        <meta property="og:title" content="Disclaimer — Policy2Summary" />
        <meta property="og:description" content="Important disclaimers about using Policy2Summary AI insurance analysis." />
        <meta property="og:type" content="website" />
        <meta property="og:url" content="https://www.policy2summary.com/disclaimer" />
      </Head>

      <nav className="border-b border-slate-200 bg-white sticky top-0 z-50">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 py-4 flex items-center gap-3">
          <div className="w-8 h-8 rounded-lg bg-emerald-600 flex items-center justify-center">
            <svg className="w-4 h-4 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
            </svg>
          </div>
          <a href="/" className="font-bold text-slate-900">Policy2Summary</a>
        </div>
      </nav>

      <main className="max-w-3xl mx-auto px-4 sm:px-6 py-12">
        <h1 className="text-3xl font-bold text-slate-900 mb-2">Disclaimer</h1>
        <p className="text-sm text-slate-500 mb-8">Please read carefully before using this service.</p>

        <div className="prose prose-slate max-w-none">
          <section className="mb-8">
            <h2 className="text-xl font-semibold text-slate-900 mb-3">AI-Generated Content</h2>
            <p className="text-slate-600 leading-relaxed mb-3">
              All summaries, analyses, and outputs provided by Policy2Summary are generated by artificial intelligence (AI). They are <strong>automated interpretations</strong> of the text in your uploaded documents and may contain errors, omissions, or misinterpretations.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-slate-900 mb-3">Not Financial, Insurance, or Legal Advice</h2>
            <p className="text-slate-600 leading-relaxed mb-3">
              Policy2Summary is <strong>not</strong> a licensed insurance broker, financial advisor, or legal service. Nothing on this site constitutes professional advice of any kind.
            </p>
            <p className="text-slate-600 leading-relaxed mb-3">
              You must always:
            </p>
            <ul className="list-disc pl-5 text-slate-600 space-y-2">
              <li>Verify coverage details directly with your insurance provider.</li>
              <li>Read the original policy document in full.</li>
              <li>Consult a licensed financial advisor or insurance broker for important decisions.</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-slate-900 mb-3">No Liability for Decisions</h2>
            <p className="text-slate-600 leading-relaxed mb-3">
              Policy2Summary and its operators disclaim all liability for any losses, damages, or adverse outcomes resulting from reliance on AI-generated summaries. This includes (but is not limited to) denied claims, coverage gaps, premium miscalculations, or missed exclusions.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-slate-900 mb-3">No Affiliation with Insurers</h2>
            <p className="text-slate-600 leading-relaxed mb-3">
              Policy2Summary is an independent tool and is <strong>not affiliated, endorsed, or partnered</strong> with any insurance company, financial institution, or regulatory body. References to specific insurers or products are for identification only.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-slate-900 mb-3">Data Privacy Reminder</h2>
            <p className="text-slate-600 leading-relaxed mb-3">
              While we do not store your documents, we strongly recommend you do not upload documents containing highly sensitive information such as full NRIC/FIN numbers, unmasked bank account numbers, passwords, or other confidential credentials.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-slate-900 mb-3">Governing Law</h2>
            <p className="text-slate-600 leading-relaxed">
              These disclaimers are governed by the laws of Singapore. Any disputes shall be resolved in accordance with Singapore law.
            </p>
          </section>
        </div>
      </main>

      <footer className="border-t border-slate-200 bg-slate-50 py-8">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 text-center text-sm text-slate-500">
          Policy2Summary — Free AI Insurance Document Reader
        </div>
      </footer>
    </div>
  );
}
