import React from 'react';
import Head from 'next/head';

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-white text-slate-800">
      <Head>
        <title>Terms of Service — Policy2Summary | Insurance Document Analyzer</title>
        <meta name="description" content="Terms of service for using Policy2Summary. By using our AI insurance document summarizer, you agree to these terms." />
        <meta name="robots" content="index, follow" />
        <link rel="canonical" href="https://policy2summary.vercel.app/terms" />
        <meta property="og:title" content="Terms of Service — Policy2Summary" />
        <meta property="og:description" content="Terms and conditions for using Policy2Summary." />
        <meta property="og:type" content="website" />
        <meta property="og:url" content="https://policy2summary.vercel.app/terms" />
      </Head>

      <nav className="border-b border-slate-200 bg-white sticky top-0 z-50">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 py-4 flex items-center gap-3">
          <div className="w-8 h-8 rounded-lg bg-emerald-600 flex items-center justify-center">
            <svg className="w-4 h-4 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
            </svg>
          </div>
          <a href="/" className="font-bold text-slate-900">Policy2Summary</a>
        </div>
      </nav>

      <main className="max-w-3xl mx-auto px-4 sm:px-6 py-12">
        <h1 className="text-3xl font-bold text-slate-900 mb-2">Terms of Service</h1>
        <p className="text-sm text-slate-500 mb-8">Last updated: {new Date().toLocaleDateString('en-SG', { year: 'numeric', month: 'long', day: 'numeric' })}</p>

        <div className="prose prose-slate max-w-none">
          <section className="mb-8">
            <h2 className="text-xl font-semibold text-slate-900 mb-3">1. Acceptance of Terms</h2>
            <p className="text-slate-600 leading-relaxed mb-3">
              By accessing or using Policy2Summary, you agree to be bound by these Terms of Service. If you do not agree, please do not use the service.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-slate-900 mb-3">2. Free Tool</h2>
            <p className="text-slate-600 leading-relaxed mb-3">
              Policy2Summary is provided as a free tool for informational purposes only. There is no charge to use the service, and no account is required.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-slate-900 mb-3">3. No Guarantee of Accuracy</h2>
            <p className="text-slate-600 leading-relaxed mb-3">
              The summaries and analyses provided by Policy2Summary are generated by artificial intelligence and are for reference only. We make no representations or warranties about the accuracy, completeness, or reliability of any analysis.
            </p>
            <p className="text-slate-600 leading-relaxed mb-3">
              You must always verify the details with your insurance provider, financial advisor, or qualified professional before making any decisions based on the analysis.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-slate-900 mb-3">4. Not Financial Advice</h2>
            <p className="text-slate-600 leading-relaxed mb-3">
              Nothing on Policy2Summary constitutes financial, insurance, legal, or professional advice. The service is a document reading aid, not a substitute for professional judgment.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-slate-900 mb-3">5. Prohibited Use</h2>
            <p className="text-slate-600 leading-relaxed mb-3">You agree not to use Policy2Summary to:</p>
            <ul className="list-disc pl-5 text-slate-600 space-y-2">
              <li>Upload documents you do not have the right to access or analyze.</li>
              <li>Upload malicious files, viruses, or any content designed to harm the service or other users.</li>
              <li>Automate or script bulk uploads in a way that degrades service performance.</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-slate-900 mb-3">6. Limitation of Liability</h2>
            <p className="text-slate-600 leading-relaxed mb-3">
              Policy2Summary and its operators are not liable for any direct, indirect, incidental, or consequential damages arising from your use of the service, including but not limited to misinterpretation of insurance coverage, missed exclusions, financial losses, or claim disputes.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-slate-900 mb-3">7. Changes to Terms</h2>
            <p className="text-slate-600 leading-relaxed">
              We may update these Terms of Service at any time. Continued use of the service after changes constitutes acceptance of the revised terms.
            </p>
          </section>
        </div>
      </main>

      <footer className="border-t border-slate-200 bg-slate-50 py-8">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 text-center text-sm text-slate-500">
          Policy2Summary — Free AI Insurance Document Reader
        </div>
      </footer>
    </div>
  );
}
